setup/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from setup import settings
from filmes.views import ListaFilmesListView, ListarFilmesCreateView, ListarFilmesDeleteView, ListarFilmesDetailView, ListarFilmesUpdateView, FilmeCreateView, FilmeDeleteView, FilmeDetailView, FilmeUpdateView, FilmeListView

urlpatterns = [
    path('', ListaFilmesListView.as_view(), name='lista_filmes_list'),
    path('create/', ListarFilmesCreateView.as_view(), name='lista_filmes_create'),
    path('<int:pk>/', ListarFilmesDetailView.as_view(), name='lista_filmes_detail'),
    path('<int:pk>/edit/', ListarFilmesUpdateView.as_view(), name='lista_filmes_update'),
    path('<int:pk>/delete/', ListarFilmesDeleteView.as_view(), name='lista_filmes_delete'),

    path('filmes/', FilmeListView.as_view(), name='filme_list'),
    path('filmes/create/', FilmeCreateView.as_view(), name='filme_create'),
    path('filmes/<int:pk>/', FilmeDetailView.as_view(), name='filme_detail'),
    path('filmes/<int:pk>/edit/', FilmeUpdateView.as_view(), name='filme_update'),
    path('filmes/<int:pk>/delete/', FilmeDeleteView.as_view(), name='filme_delete'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

filmes/models.py
from django.db import models
from django.core.validators import FileExtensionValidator

class Filme(models.Model):
    titulo = models.CharField(max_length=100)
    diretor = models.CharField(max_length=100)
    capa = models.ImageField(upload_to='capas/', validators=[FileExtensionValidator(['png','jpng','jpg'])])
    def __str__(self):
        return f"{self.titulo}-{self.diretor}"
    
class ListFilmes(models.Model):
    nome = models.CharField(max_length=100)
    filmes = models.ManyToManyField(Filme)

    def __str__(self):
        return self.nome

filmes/forms.py
from django import forms
from .models import ListFilmes, Filme

class ListFilmesForm(forms.ModelForm):
    class Meta:
        model = ListFilmes
        fields = '__all__'

class FilmeForm(forms.ModelForm):
    class Meta:
        model = Filme
        fields = '__all__'

filmes/views.py
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView,DeleteView
from django.shortcuts import render
from filmes.forms import FilmeForm, ListFilmesForm
from filmes.models import Filme, ListFilmes

class ListaFilmesListView(ListView):
    model = ListFilmes
    context_object_name = 'listfilm'
    template_name = 'listfilme/listfilm_list.html'
    paginate_by = 8
    queryset = ListFilmes.objects.order_by('-id')

class ListarFilmesDetailView(DetailView):
    model = ListFilmes
    context_object_name = 'listfilm'
    template_name = 'listfilme/listfilm_detail.html'

class ListarFilmesCreateView(CreateView):
    model = ListFilmes
    form_class = ListFilmesForm
    template_name = 'listfilme/listfilm_form.html'
    success_url = reverse_lazy('lista_filmes_list')

class ListarFilmesUpdateView(UpdateView):
    model = ListFilmes
    fields = ['nome', 'filmes']
    template_name = 'listfilme/listfilm_form.html'
    success_url = reverse_lazy('lista_filmes_list')

class ListarFilmesDeleteView(DeleteView):
    model = ListFilmes
    template_name = 'listfilme/listfilm_confirm_delete.html'
    success_url = reverse_lazy('lista_filmes_list')



#filme
class FilmeListView(ListView):
    model = Filme
    context_object_name = 'filme'
    template_name = 'filme/filme_list.html'

class FilmeDetailView(DetailView):
    model = Filme
    template_name = 'filme/filme_detail.html'

class FilmeCreateView(CreateView):
    model = Filme
    form_class = FilmeForm
    template_name = 'filme/filme_form.html'
    
class FilmeUpdateView(UpdateView):
    model = Filme
    form_class = FilmeForm
    template_name = 'filme/filme_form.html'
    success_url = reverse_lazy('filme_list')

class FilmeDeleteView(DeleteView):
    model = Filme
    template_name = 'filme/filme_confirm_delete.html'
    success_url = reverse_lazy('filme_list')

filmes/templates/base.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    {% load bootstrap5 %}
    {% load static %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">Lista de Filmes</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'lista_filmes_list' %}">Lista de filmes</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'filme_list' %}">Filmes</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

filmes/templates/filme/filme_confirm_delete.html
{% extends "base.html" %}
{% block content %}
<h1>Confirmar Exclusão</h1>
<p>Tem certeza que deseja excluir o filme "{{ object.nome }}"?</p>
<form method="POST">
    {% csrf_token %}
    <input type="submit" value="Sim">
    <a href="{% url 'filme_detail' object.pk %}">Não</a>
</form>
{% endblock  %}

filmes/templates/filme/filme_detail.html
{% extends "base.html" %}
{% block content %}
<h2>{{ object.titulo }}</h2>
<p>Artista: {{ object.diretor }}</p>
<p>lists de filmes:
    {% for listfilmes in object.listfilmes_set.all %}
        {{ listfilmes.nome }}
    {% endfor %}
</p>
{% endblock  %}

filmes/templates/filme/filme_form.html
{% extends "base.html" %}
{% block content %}
<h1>{% if form.instance.pk %}Editar{% else %}Criar{% endif %} Filme</h1>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Salvar</button>
</form>
{% endblock  %}

filmes/templates/filme/filme_list.html
{%extends "base.html"%}
{%block content%}

<h2>Todos os filmes</h2>

<a href="{%url 'filme_create'%}" class="btn btn-primary mb-3">Cirar filme</a>

<ul>
    {% for filme in object_list %}
    <li>{{filme.titulo}} - {{filme.diretor}}
        <img src="{{filme.capa.url}}" alt="{{filme.titulo}}" width=100>
        <a href="{%url 'filme_detail' filme.pk%}" class="btn btn-primary">Detalhes</a>
        <a href="{% url 'filme_update' filme.pk %}" class="btn btn-secondary">Editar</a>
        <a href="{% url 'filme_delete' filme.pk %}" class="btn btn-danger">Excluir</a>
    </li>
    {%endfor%}
</ul>
{% endblock %}

filmes/templates/listfilme/listfilm_confirm_delete.html
{% extends "base.html" %}
{% block content %}
    <h1>Confirmar Exclusão</h1>
    <p>Tem certeza que deseja excluir a lista de filme "{{ object.nome }}"?</p>
    <form method="POST">
        {% csrf_token %}
        <input type="submit" value="Sim">
        <a href="{% url 'lista_filmes_detail' object.pk %}">Não</a>
    </form>
{% endblock  %}

filmes/templates/listfilme/listfilm_detail.html
{% extends 'base.html' %}

{% block content %}

<h2>{{ listfilm.nome }}</h2>
<ul>
    {% for filme in listfilm.filmes.all %}
    <li>{{ filme.titulo }} - {{ filme.diretor }} - <img src="{{ filme.capa.url }}" alt="{{ filme.titulo }}" width=100></li>
    {% endfor %}
</ul>
<a href="{% url 'lista_filmes_update' listfilm.pk %}">Editar</a>
<a href="{% url 'lista_filmes_delete' listfilm.pk %}">Excluir</a>

{% endblock %}

filmes/templates/listfilme/listfilm_form.html
{% extends "base.html" %}
{% block content %}
    <h1>{% if form.instance.pk %}Editar{% else %}Criar{% endif %} Lista de filmes</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Salvar</button>
    </form>
{% endblock  %}

filmes/templates/listfilme/listfilm_list.html
{% extends "base.html" %}
{% block content %}
<a href="{% url "lista_filmes_create" %}" class="btn btn-primary mb-3">Criar lista de filmes</a>
{% for listfilm in listfilm %}
<li>
    {{ listfilm.nome }}
   
    <a href="{% url 'lista_filmes_detail' listfilm.pk %}">Detalhes</a>
    <a href="{% url 'lista_filmes_update' listfilm.pk %}">Editar</a>
    <a href="{% url 'lista_filmes_delete' listfilm.pk %}">Excluir</a>
</li>
{% endfor %}
</ul>
{% endblock %}